// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDySqNt2R3FBRecm0qf4nJkn14NGcyEBrI',
    appId: '1:500532918298:web:68098ced8688ec7eec39a3',
    messagingSenderId: '500532918298',
    projectId: 'dictation-tutor',
    authDomain: 'dictation-tutor.firebaseapp.com',
    storageBucket: 'dictation-tutor.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdXZCeJgbyogm1C4Ys8kXjbtRtBdaXlN8',
    appId: '1:500532918298:android:5b3f5425d70132dbec39a3',
    messagingSenderId: '500532918298',
    projectId: 'dictation-tutor',
    storageBucket: 'dictation-tutor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZoU9LmntvBiXoEMOKyWO6jUZtHpkg5Iw',
    appId: '1:500532918298:ios:08142658f056a05bec39a3',
    messagingSenderId: '500532918298',
    projectId: 'dictation-tutor',
    storageBucket: 'dictation-tutor.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );
}
